runtime: python27
threadsafe: true

handlers:
  # So we can have our static directory uploaded and available.
  # Don't put anything in this folder that isn't public.
  - url: /static/*
    static_dir: static

  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /js/*
    static_dir: js

  - url: /photography/.*
    script: photography.app
    secure: always

  - url: /admin/.*
    script: admin.app
    secure: always
    login: required

  # The default route, also the fall back route
  # Used for the home page currently
  - url: /.*
    script: main.app
    secure: always


# Any file patterns to skip when uploading to App Engine
skip_files:
  - ^(.*/)?.*\.py[co]$
